on: [push]

name: ci

jobs:
  build:
    runs-on: ubunt-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.71.0
          target: wasm32-unknown-unknown
          components: clippy
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Annotate commit with clippy warnings
        run: cargo clippy --all-targets --all-features -- -D warnings
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run test
      - run: npm run build
